### ISSUE TITLE
announcing group messages to the whole fediverse is spammy

### ISSUE THREAD

**Issue by Johann150** [michaelcpuckett/activitypub-core#11]
As far as I understand, the groups plugin sends `Announce`s to all known inboxes:

https://github.com/michaelcpuckett/activitypub-core/blob/34d57d2d7f89bf48da698116273dc86240f2f088/packages/activitypub-core-plugin-groups/src/index.ts#L212

I was wondering why some posts where showing up on my single user instance's global timeline when I noticed that they were `Announce`d by an actor from `chirp.social`. My general expectation is that activities are only sent to following actors, otherwise this is sending bulk unsolicited content.

**Comment by michaelcpuckett** [comment]
@Johann150

Hi, sorry about the concern, but I am just trying to implement the ActivityPub spec:

> If an object is addressed to the [Public](https://www.w3.org/TR/activitypub/#public-addressing) special collection, a server MAY deliver that object to all known sharedInbox endpoints on the network.

I'm sorry (and see how) you consider this spammy, but I think that the "global timeline" is supposed to contain all Public posts from all peer servers, so I don't think this is an issue.

Furthermore:

> While no specific mechanism for combating spam is provided in ActivityPub, it is recommended that servers filter incoming content both by local untrusted users and any remote users through some sort of spam filter.

You are free to block the chirp.social server but I hope that is only as a last resort.

Thank you!

**Comment by michaelcpuckett** [comment]
Returning to this...

https://socialhub.activitypub.rocks/t/federated-timeline-view/3082

Based on feedback from other ActivityPub devs, I've turned this off in the main package and this change should come to chirp.social soon.
